apiVersion: v1
kind: Pod
metadata:
  labels:
    run: podtest2
  name: podtest2 #nombre del pod
  namespace: default
spec: # qur contenedor se desea crear
  containers:
  - image: httpd:alpine
    imagePullPolicy: IfNotPresent
    name: cont2 # nombre del contenedor (puede ser dif. nombre del pod)