apiVersion: v1
kind: Pod
metadata:
  labels: # sirven para que los objetos de mayor nivel (replicSet o Deployment) puedan administar los pods
    run: podtest2
    name: front
    env: DESA
  name: podtest2 #nombre del pod
  namespace: default
spec: # qur contenedor se desea crear
  containers:
  - image: httpd:alpine
    imagePullPolicy: IfNotPresent
    name: cont2 # nombre del contenedor (puede ser dif. nombre del pod)
---
apiVersion: v1
kind: Pod
metadata:
  labels: # sirven para que los objetos de mayor nivel (replicSet o Deployment) puedan administar los pods
    run: podtest3
    name: back
    env: DESA
  name: podtest3 #nombre del pod
  namespace: default
spec: # qur contenedor se desea crear
  containers:
  - image: nginx:alpine
    imagePullPolicy: IfNotPresent
    name: cont3 # nombre del contenedor (puede ser dif. nombre del pod)