apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    name: prod
  annotations:
    message: "Creacion de Namespace para ambiente desarrollo"
    maintainer: Diego Quiroz Ramirez
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-demo
  namespace: prod
spec:
  hard:
    limits.cpu: "2"
    limits.memory: 2Gi
    requests.cpu: "2"
    requests.memory: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: prod
  labels:
    app: nginx
  annotations:
    kubernetes.io/change-cause: "Correccion del nombre y tag de la imagen del contenedor"
spec:
  revisionHistoryLimit: 5
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: python:3.6-alpine
        command: ['sh', '-c', 'echo contDos2 > index.html && python -m http.server 8082']
        ports:
        - containerPort: 8082
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "1"
            memory: "1Gi"