apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: python
  annotations:
    kubernetes.io/change-cause: "Add env HOSTNAME to indentity pod"
spec:
  revisionHistoryLimit: 5
  replicas: 3
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: python:3.6-alpine
        command: ['sh', '-c', 'echo $HOSTNAME > index.html && python -m http.server 8082']
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: mgnix-service
  labels:
    app: python
spec:
  type: ClusterIP
  selector:
    app: python
  ports:
    - protocol: TCP
      port: 8080 # puerto del servicio del service
      targetPort: 8082 # puerto del los pods