apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: python
  annotations:
    kubernetes.io/change-cause: "Add env HOSTNAME to indentity pod"
spec:
  revisionHistoryLimit: 5
  replicas: 3
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: python:3.6-alpine
        command: ['sh', '-c', 'echo $HOSTNAME > index.html && python -m http.server 8082']
        resources:
          limits:
            cpu: "2"
            memory: 512Mi
          requests:
            cpu: "0.2"
            memory: 256Mi
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: mgnix-service
  labels:
    app: python
spec:
  type: NodePort
  selector:
    app: python
  ports:
    - protocol: TCP
      port: 80 # puerto del servicio del service
      targetPort: 8082 # puerto del los pods
      nodePort: 30000 # exponer puerto del services con NodePort