apiVersion: v1
kind: ConfigMap
metadata:
  name: db-demo-envs
data:
  env-prod: |
    HOST_DATA_BASE=10.10.10.10
    NAME_DATA_BASE=BDTEST123456
    PORT_DATA_BASE=3306
    PORT=7000
    PASSWORD_DATA_BASE="123asdf2342%$#S"