apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: jenkins
  name: role-diego-monitoring
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"] #all values "*"
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"] #all values "*"