apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding-diego-monitoring
  namespace: jenkins
subjects:
- kind: ServiceAccount
  name: sa-diego
  apiGroup: ""
roleRef:
  kind: Role
  name: role-diego-monitoring
  apiGroup: rbac.authorization.k8s.io