apiVersion: v1
kind: Pod
metadata:
  labels: # sirven para que los objetos de mayor nivel (replicSet o Deployment) puedan administar los pods
    run: podtest
    name: front
    env: DESA
  name: pod-diego-monitoring #nombre del pod
  namespace: default
spec: # que contenedor se desea crear
  containers:
  - image: jenkins/jenkins
    imagePullPolicy: IfNotPresent
    name: cont2 # nombre del contenedor (puede ser dif. nombre del pod)
  serviceAccountName: sa-diego
  #automountServiceAccountToken: false