apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: app
    image: polinux/stress
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "86M", "--vm-hang", "1"]