apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-cluster
  labels:
    app: jenkins
  annotations:
    kubernetes.io/change-cause: "Add env HOSTNAME to indentity pod"
spec:
  #revisionHistoryLimit: 5
  #replicas: 3
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    app: jenkins
spec:
  type: ClusterIP
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 8080 # puerto del servicio del service
      targetPort: 8082 # puerto del los pods