apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: python
  annotations:
    kubernetes.io/change-cause: "Add env HOSTNAME to indentity pod"
spec:
  revisionHistoryLimit: 5
  replicas: 3
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: python:3.6-alpine
        command: ['sh', '-c', 'echo $HOSTNAME > index.html && python -m http.server 80']
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: internal-python-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  selector:
    app: python
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: external-python-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
spec:
  selector:
    app: python
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80