apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    name: prod
  annotations:
    message: "Creacion de Namespace para ambiente desarrollo"
    maintainer: Diego Quiroz Ramirez
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-min-max-demo-lr
  namespace: prod
spec:
  limits:
  - max:
      memory: 1Gi
      cpu: "1"
    min:
      memory: 100Mi
      cpu: "0.1"
    type: Container
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: podtest3
    name: back
    env: DESA
  name: podtest3
  namespace: prod
spec:
  containers:
  - image: nginx:alpine
    imagePullPolicy: IfNotPresent
    name: cont3
    resources:
      limits:
        memory: 800Mi
        cpu: 900m
      requests:
        memory: 100Mi
        cpu: 100m