apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: envar-demo-container
    image: nginx:alpine
    command: ['sh', '-c', "echo Esta es la version ${VERSION} y modulo ${MODULE} > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"]
    env:
    - name: VERSION
      value: "1.0"
    - name: MODULE
      value: "MOD-001"
    command: ["/bin/echo"]
    args: ["$(VERSION)", "$(MODULE)"]
  restartPolicy: OnFailure
