apiVersion: apps/v1
kind: Deployment
metadata:
  name: swg-deployment
  labels:
    app: swg
  annotations:
    kubernetes.io/change-cause: "Add env HOSTNAME to indentity pod"
spec:
  revisionHistoryLimit: 5
  replicas: 3
  selector:
    matchLabels:
      app: swg
  template:
    metadata:
      labels:
        app: swg
    spec:
      containers:
      - name: swg-mock
        image: 222522/swg_challenge_code:4.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /docs
            port: 8080
            #httpHeaders: #Array opional
            #  - name: Authorization
            #    value: Authorization
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 2 #Max 3 Min 1
          successThreshold: 1 #Min 1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: swg-service
  labels:
    app: swg
spec:
  type: NodePort
  selector:
    app: swg
  ports:
    - protocol: TCP
      port: 80 # puerto del servicio del service
      targetPort: 8080 # puerto del los pods
      nodePort: 30000