apiVersion: v1
kind: ConfigMap
metadata:
  name: db-demo-envs
data:
  ENV-DESA: |+
    #Data Info DB
    #HOST_DATA_BASE in secrets
    NAME_DATA_BASE=BDDESA123456
    PORT_DATA_BASE=3306
    #PASSWORD_DATA_BASE in secrets
    #Data Info Application
    PORT=${PORT}
  ENV-TEST: |+
    #Data Info DB
    #HOST_DATA_BASE in secrets
    NAME_DATA_BASE=BDTEST123456
    PORT_DATA_BASE=3306
    #PASSWORD_DATA_BASE in secrets
    #Data Info Application
    PORT=${PORT}    
  ENV-PROD: |+
    #Data Info DB
    #HOST_DATA_BASE in secrets
    NAME_DATA_BASE=BDPROD123456
    PORT_DATA_BASE=3306
    #PASSWORD_DATA_BASE in secrets
    #Data Info Application
    PORT=${PORT}
  NODE_ENV_DESA: "desa"
  NODE_ENV_TEST: "test"
  NODE_ENV_PROD: "prod"