---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  labels:
    app: app
  annotations:
    kubernetes.io/change-cause: "Nuevo Set de Variables"
    configmap.reloader.stakater.com/reload: "db-demo-envs"
spec:
  revisionHistoryLimit: 5
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: app-config:v4
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: config
            mountPath: /app/dotenv/config/
        env:
          - name: PORT
            valueFrom:
              secretKeyRef:
                name: secret-db-demo
                key: HOST_DATA_BASE_DESA
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: db-demo-envs
                key: NODE_ENV_DESA #Dinamico
          - name: HOST_DATA_BASE
            valueFrom:
              secretKeyRef:
                name: secret-db-demo
                key: HOST_DATA_BASE_DESA
          - name: PASSWORD_DATA_BASE
            valueFrom:
              secretKeyRef:
                name: secret-db-demo
                key: PASSWORD_DATA_BASE_DESA
      volumes:
        - name: config
          configMap:
            name: db-demo-envs
            items:
              - key: ENV-DESA #Dinamico
                path: desa.env #Nombre del archivo #Dinamico

# NOTAS: comando para restart el deployment luego de actualizar el configMap
# $ kubectl rollout restart deployment <name_deployment>