apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: mock-hpa
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: server-mock
    minReplicas: 2
    maxReplicas: 10
    metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageValue: 128Mi