apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster-mock-server
  region: us-east-2

nodeGroups:
  - name: scale-east1c
    instanceType: t2.small #t2.small
    desiredCapacity: 1
    maxSize: 2
    availabilityZones: ["us-east-2c"]
    iam:
      withAddonPolicies:
        autoScaler: true
    labels:
      nodegroup-type: stateful-east1c
      instance-type: onDemand
    ssh: # use existing EC2 key
      publicKeyName: eks-key-pair