apiVersion: v1
kind: Secret
metadata:
  name: secret-db-demo
type: Opaque
data:
  HOST_DATA_BASE_DESA: $HOST_DATA_BASE_DESA
  PASSWORD_DATA_BASE_DESA: $PASSWORD_DATA_BASE_DESA
  PORT_DESA: $PORT_DESA

##Code Los valores deben estar en bas64: echo <valor> | base64
##Decode Los valores en base 64: echo <valor_bas64> | base64 -d
## Para evitar la decodificacion usar:  envsubst < 01-secret.yaml > example/01-secret-tmp.yaml donde tmp no debe versionarse